### ISSUE TITLE
PDF MVW F-Stage no outline

### ISSUE THREAD

**Issue by M3ssman** [ulb-sachsen-anhalt/digital-derivans#10]
### Issue description

When PDF for a subsequent digitalisate is created (like a F-stage from a multivolume work), currently there's no outline created and added for Navigation

### Steps to reproduce the issue

1. Start Derivans for F-Stage process

### What's the expected result?
- PDF contains outline

### What's the actual result?
- PDF lacks outline

### Plattform
- Ubuntu 18.04 LTS / Ubuntu 20.04 LTS
- JDK 11

**Comment by M3ssman** [comment]
Actually, this is an enhancement, since it was done only for digital stuff marked as logical `monograph`

**Comment by galdring** [comment]
has been implemented
