### ISSUE TITLE
Next Version PDF Processing

### ISSUE THREAD

**Issue by M3ssman** [ulb-sachsen-anhalt/digital-derivans#13]
## Description

As the actual used Library, iText5, is already reasonably out-dated and no longer active maintained, a replacement for the current PDF-processing is required.

Still subject to change, whether this will be done using next iText version (iText7) or a completely different library.

**Comment by bertsky** [comment]
Have a look at https://github.com/internetarchive/archive-pdf-tools – this contains a very efficient sandwich maker.

**Comment by M3ssman** [comment]
Thanks for the suggestion! 
<Have you | Did you hear> of experiences using this tool? 

Before I turned to iText back about 2 years ago, I tried  [PyMuPDF](https://github.com/pymupdf/PyMuPDF) (which seems to be used by archive-pdf-tools), [PyPDF4](https://github.com/claird/PyPDF4), [pypdf](https://github.com/py-pdf/pypdf) and [Apache PDFBox](https://github.com/apache/pdfbox), which was used by the proprietary tool itself I had to replace (=original motivation to do this). I failed with all of them to create PDFs with 2.500+ regular size pages or 1000+ newspaper pages. PrimaLab itself uses iText for [prima-page-converter](https://github.com/PRImA-Research-Lab/prima-page-converter), and luckily I found out that this is able to generate/stream PDF files even for prints with 3.600+ pages.

**Comment by bertsky** [comment]
> <Have you | Did you hear> of experiences using this tool?

It's used massively within IA OpenLibrary AFAIK. They had to ensure it's super efficient due to sheer scale. The MRC idea is a bit like DjVu IIUC. And with inputs like hOCR, ALTO or PAGE, we do have text coordinates ready, so its easy to get the mask.

Besides MuPDF they also use the PDF renderer from Tesseract for some reason.

**Comment by M3ssman** [comment]
Switched to iText8
