### ISSUE TITLE
PDF Textlayer missing

### ISSUE THREAD

**Issue by M3ssman** [ulb-sachsen-anhalt/digital-derivans#48]
# Description

Derivans fails to include proper text layer in PDF files although OCR data is present in METS in common file group `FULLTEXT`.
Originates from works in case of #47 .

**Comment by einspunktnull** [comment]
fix provided in branch [fix/#48_pdf_layer](https://github.com/ulb-sachsen-anhalt/digital-derivans/tree/fix/%2348_pdf_textlayer)
