### ISSUE TITLE
Review Descriptive Metadata

### ISSUE THREAD

**Issue by M3ssman** [ulb-sachsen-anhalt/digital-derivans#5]
Currently, if METS/MODS data is available, under some special circumstances the following descriptive Metadata is missing or at least questionable:

* Person (as author or editor)
* Year (with retrodigitalisates: original publication)

**Comment by adendogo** [comment]
this issue is fixed, but questionable remains the occurence of such _circumstances_

**Comment by M3ssman** [comment]
Please note, that especially in old prints back in the dark ages it was quite common to introduce oneself only as publisher for political reasons.
