### ISSUE TITLE
PDF naming for Kitodo2 MVW

### ISSUE THREAD

**Issue by M3ssman** [ulb-sachsen-anhalt/digital-derivans#9]
## Issue description

When a PDF for a f-stage MVW is created, it is named like the c-stage PPN, not like the f-stage.

### Steps to reproduce the issue

1. Start Derivans with data layout for f-stage 

### What's the expected result?
- PDF is named with GVK-PPN for f-stage

### What's the actual result?
- PDF is named with GVK-PPN for c-stage

### Plattform
- Ubuntu 18.04 LTS / Ubuntu 20.04 LTS
- JDK 11

**Comment by galdring** [comment]
fixed
